# ============================================================
# Dockerfile.mlflow
# ghcr.io/mlflow/mlflow:v2.13.0 기반에 psycopg2 + boto3 추가
# ============================================================
FROM ghcr.io/mlflow/mlflow:v2.13.0

RUN pip install --no-cache-dir \
    psycopg2-binary==2.9.9 \
    boto3==1.34.101
